// Comprehensive destination database with real attractions, restaurants, and hotels
export const destinations = {
  paris: {
    name: "Paris",
    country: "France",
    overview:
      "Explore the City of Light with iconic landmarks, world-class museums, and exquisite cuisine",
    description: "The capital of France, known for art, fashion, gastronomy, and culture",
    coordinates: { lat: 48.8566, lng: 2.3522 },
    bestTime: "April-June, September-October",
    language: "French",
    currency: "EUR",
    timezone: "CET",
    attractions: [
      {
        name: "Eiffel Tower",
        category: "Monument",
        description: "Iconic iron lattice tower with panoramic city views",
        timeToSpend: "2-3 hours",
        cost: "$12-18",
        openHours: "9:00 AM - 12:45 AM",
      },
      {
        name: "Louvre Museum",
        category: "Museum",
        description: "World's largest art museum, home to the Mona Lisa",
        timeToSpend: "3-4 hours",
        cost: "$17",
        openHours: "9:00 AM - 6:00 PM",
      },
      {
        name: "Notre-Dame Cathedral",
        category: "Historical",
        description: "Stunning Gothic cathedral with intricate architecture",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "8:00 AM - 6:45 PM",
      },
      {
        name: "Arc de Triomphe",
        category: "Monument",
        description: "Triumphal arch with views over Champs-Élysées",
        timeToSpend: "1-2 hours",
        cost: "$13",
        openHours: "10:00 AM - 10:30 PM",
      },
      {
        name: "Champs-Élysées",
        category: "Shopping",
        description: "Famous avenue with shops, cafes, and street performances",
        timeToSpend: "2-3 hours",
        cost: "Varies",
        openHours: "All day",
      },
    ],
    restaurants: {
      breakfast: [
        {
          name: "Café de Flore",
          cuisine: "French",
          description: "Historic café famous for hot chocolate and croissants",
          priceRange: "$$",
          rating: 4.5,
        },
        {
          name: "Les Deux Magots",
          cuisine: "French",
          description: "Legendary café with literary history and pastries",
          priceRange: "$$",
          rating: 4.4,
        },
        {
          name: "Ladurée",
          cuisine: "French",
          description: "Luxury pastry shop and breakfast spot, known for macarons",
          priceRange: "$$$",
          rating: 4.6,
        },
      ],
      lunch: [
        {
          name: "L'Ami Jean",
          cuisine: "French",
          description: "Cozy bistro serving classic French comfort food",
          priceRange: "$$",
          rating: 4.5,
        },
        {
          name: "Bistrot Paul Bert",
          cuisine: "French",
          description: "Traditional bistro with excellent wine selection",
          priceRange: "$$",
          rating: 4.4,
        },
        {
          name: "Chez Janou",
          cuisine: "French",
          description: "Provençal-style bistro with rustic charm",
          priceRange: "$$",
          rating: 4.3,
        },
      ],
      dinner: [
        {
          name: "Le Bernardin",
          cuisine: "French Seafood",
          description: "Michelin-starred restaurant specializing in seafood",
          priceRange: "$$$",
          rating: 4.8,
        },
        {
          name: "L'Astrance",
          cuisine: "French",
          description: "Three Michelin-star fine dining restaurant",
          priceRange: "$$$",
          rating: 4.9,
        },
        {
          name: "Mirazur",
          cuisine: "Mediterranean",
          description: "Michelin-starred cuisine with ocean views",
          priceRange: "$$$",
          rating: 4.7,
        },
      ],
    },
    hotels: [
      {
        name: "Le Meurice",
        type: "Luxury Hotel",
        location: "Tuileries",
        description: "Iconic palace hotel with impeccable service",
        pricePerNight: "$600-1200",
        rating: 4.8,
        amenities: ["Spa", "Michelin Restaurant", "Concierge"],
      },
      {
        name: "Ritz Paris",
        type: "Luxury Hotel",
        location: "Place Vendôme",
        description: "Historic luxury hotel with legendary service",
        pricePerNight: "$700-1500",
        rating: 4.8,
        amenities: ["Pool", "Fine Dining", "Spa"],
      },
      {
        name: "Hotel de Crillon",
        type: "Luxury Hotel",
        location: "Champs-Élysées",
        description: "18th-century palace converted to luxury hotel",
        pricePerNight: "$500-1000",
        rating: 4.7,
        amenities: ["Spa", "Restaurants", "Bar"],
      },
      {
        name: "Hôtel Plaza Athénée",
        type: "Upscale Hotel",
        location: "Champs-Élysées",
        description: "Elegant hotel known for style and hospitality",
        pricePerNight: "$400-800",
        rating: 4.6,
        amenities: ["Restaurant", "Spa", "Bar"],
      },
    ],
    budget: {
      budget: { accommodation: "$50-100/night", food: "$25-40/day", activities: "$30-50/day" },
      medium: { accommodation: "$150-300/night", food: "$60-100/day", activities: "$50-100/day" },
      luxury: { accommodation: "$500+/night", food: "$150+/day", activities: "$100+/day" },
    },
  },
  tokyo: {
    name: "Tokyo",
    country: "Japan",
    overview:
      "Experience the blend of ancient tradition and cutting-edge modernity in Japan's vibrant capital",
    description: "A metropolis seamlessly blending traditional temples with futuristic technology",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    bestTime: "March-May, September-November",
    language: "Japanese",
    currency: "JPY",
    timezone: "JST",
    attractions: [
      {
        name: "Senso-ji Temple",
        category: "Religious",
        description: "Tokyo's oldest temple with stunning architecture",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "6:00 AM - 5:00 PM",
      },
      {
        name: "Tokyo Skytree",
        category: "Modern",
        description: "Tallest structure in Japan with observation decks",
        timeToSpend: "2-3 hours",
        cost: "$18-25",
        openHours: "8:00 AM - 10:00 PM",
      },
      {
        name: "Shibuya Crossing",
        category: "Culture",
        description: "World's busiest pedestrian crossing",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "All day",
      },
      {
        name: "Meiji Shrine",
        category: "Religious",
        description: "Peaceful shrine surrounded by forests",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "Sunrise - Sunset",
      },
      {
        name: "Akihabara",
        category: "Shopping",
        description: "Electric town with tech and anime culture",
        timeToSpend: "2-3 hours",
        cost: "Varies",
        openHours: "All day",
      },
    ],
    restaurants: {
      breakfast: [
        {
          name: "Tsukiji Outer Market",
          cuisine: "Japanese",
          description: "Fresh sushi and seafood breakfast",
          priceRange: "$$",
          rating: 4.4,
        },
        {
          name: "Mos Burger",
          cuisine: "Japanese Fast Food",
          description: "Popular burger chain with rice burgers",
          priceRange: "$",
          rating: 4.2,
        },
        {
          name: "Yoshinoya",
          cuisine: "Japanese",
          description: "Bowl of beef and rice breakfast",
          priceRange: "$",
          rating: 4.1,
        },
      ],
      lunch: [
        {
          name: "Ichiran Ramen",
          cuisine: "Ramen",
          description: "Famous Fukuoka-style ramen",
          priceRange: "$",
          rating: 4.5,
        },
        {
          name: "Gonpachi",
          cuisine: "Japanese",
          description: "Lively izakaya with diverse menu",
          priceRange: "$$",
          rating: 4.3,
        },
        {
          name: "Nabezo",
          cuisine: "Japanese Hot Pot",
          description: "Interactive hot pot dining experience",
          priceRange: "$$",
          rating: 4.4,
        },
      ],
      dinner: [
        {
          name: "Sukiyabashi Jiro",
          cuisine: "Sushi",
          description: "Three Michelin-star sushi restaurant",
          priceRange: "$$$",
          rating: 4.9,
        },
        {
          name: "Goro Ramen",
          cuisine: "Ramen",
          description: "Award-winning tonkotsu ramen",
          priceRange: "$$",
          rating: 4.6,
        },
        {
          name: "Kanda",
          cuisine: "Sushi",
          description: "Michelin-starred intimate sushi bar",
          priceRange: "$$$",
          rating: 4.8,
        },
      ],
    },
    hotels: [
      {
        name: "Mandarin Oriental Tokyo",
        type: "Luxury Hotel",
        location: "Nihonbashi",
        description: "Modern luxury with traditional Japanese service",
        pricePerNight: "$400-800",
        rating: 4.8,
        amenities: ["Spa", "Fine Dining", "Concierge"],
      },
      {
        name: "Peninsula Tokyo",
        type: "Luxury Hotel",
        location: "Ginza",
        description: "Contemporary luxury hotel in shopping district",
        pricePerNight: "$350-700",
        rating: 4.7,
        amenities: ["Spa", "Restaurants", "Bar"],
      },
      {
        name: "Park Hyatt Tokyo",
        type: "Luxury Hotel",
        location: "Shinjuku",
        description: "High-rise luxury with panoramic views",
        pricePerNight: "$400-900",
        rating: 4.8,
        amenities: ["Pool", "Spa", "Fine Dining"],
      },
    ],
    budget: {
      budget: { accommodation: "$40-80/night", food: "$20-35/day", activities: "$25-40/day" },
      medium: { accommodation: "$120-250/night", food: "$50-80/day", activities: "$40-70/day" },
      luxury: { accommodation: "$400+/night", food: "$120+/day", activities: "$80+/day" },
    },
  },
  newyork: {
    name: "New York",
    country: "USA",
    overview: "Discover the energy of the Big Apple with world-famous attractions and diverse neighborhoods",
    description: "The city that never sleeps, known for Broadway, museums, and cosmopolitan culture",
    coordinates: { lat: 40.7128, lng: -74.006 },
    bestTime: "September-November, March-May",
    language: "English",
    currency: "USD",
    timezone: "EST",
    attractions: [
      {
        name: "Statue of Liberty",
        category: "Monument",
        description: "Iconic symbol of freedom with harbor views",
        timeToSpend: "2-3 hours",
        cost: "$24",
        openHours: "9:00 AM - 5:00 PM",
      },
      {
        name: "Central Park",
        category: "Park",
        description: "843-acre urban park with trails, lakes, and attractions",
        timeToSpend: "2-4 hours",
        cost: "Free",
        openHours: "All day",
      },
      {
        name: "Times Square",
        category: "Culture",
        description: "Famous intersection with theaters and neon signs",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "All day",
      },
      {
        name: "Empire State Building",
        category: "Monument",
        description: "Art Deco skyscraper with observation decks",
        timeToSpend: "2-3 hours",
        cost: "$37",
        openHours: "8:00 AM - 2:00 AM",
      },
      {
        name: "The Met Museum",
        category: "Museum",
        description: "World's largest art museum",
        timeToSpend: "3-5 hours",
        cost: "$28",
        openHours: "10:00 AM - 5:30 PM",
      },
    ],
    restaurants: {
      breakfast: [
        {
          name: "Balthazar",
          cuisine: "French",
          description: "Iconic SoHo brasserie with French breakfast",
          priceRange: "$$",
          rating: 4.4,
        },
        {
          name: "Sarabeth's",
          cuisine: "American",
          description: "New York institution for breakfast",
          priceRange: "$$",
          rating: 4.3,
        },
        {
          name: "Black Tap",
          cuisine: "American Diner",
          description: "Trendy diner with creative breakfast",
          priceRange: "$$",
          rating: 4.2,
        },
      ],
      lunch: [
        {
          name: "Shake Shack",
          cuisine: "American",
          description: "Famous burger chain from New York",
          priceRange: "$",
          rating: 4.4,
        },
        {
          name: "Joe's Pizza",
          cuisine: "Italian",
          description: "Legendary New York style pizza",
          priceRange: "$",
          rating: 4.5,
        },
        {
          name: "Katz's Delicatessen",
          cuisine: "Jewish",
          description: "Historic deli famous for pastrami sandwiches",
          priceRange: "$$",
          rating: 4.4,
        },
      ],
      dinner: [
        {
          name: "Per Se",
          cuisine: "French",
          description: "Three Michelin-star fine dining",
          priceRange: "$$$",
          rating: 4.8,
        },
        {
          name: "Eleven Madison Park",
          cuisine: "Contemporary",
          description: "Michelin-starred innovative cuisine",
          priceRange: "$$$",
          rating: 4.7,
        },
        {
          name: "Carbone",
          cuisine: "Italian",
          description: "Upscale Italian dining in Greenwich Village",
          priceRange: "$$",
          rating: 4.6,
        },
      ],
    },
    hotels: [
      {
        name: "The Plaza",
        type: "Luxury Hotel",
        location: "Fifth Avenue",
        description: "Iconic hotel overlooking Central Park",
        pricePerNight: "$500-1200",
        rating: 4.7,
        amenities: ["Spa", "Fine Dining", "Bar"],
      },
      {
        name: "Peninsula New York",
        type: "Luxury Hotel",
        location: "Midtown",
        description: "Modern luxury with impeccable service",
        pricePerNight: "$400-900",
        rating: 4.7,
        amenities: ["Spa", "Restaurants", "Rooftop Bar"],
      },
      {
        name: "Four Seasons",
        type: "Luxury Hotel",
        location: "Midtown",
        description: "Contemporary luxury hotel",
        pricePerNight: "$450-1000",
        rating: 4.7,
        amenities: ["Spa", "Fine Dining", "Bar"],
      },
    ],
    budget: {
      budget: { accommodation: "$80-150/night", food: "$30-50/day", activities: "$30-60/day" },
      medium: {
        accommodation: "$200-400/night",
        food: "$70-120/day",
        activities: "$60-120/day",
      },
      luxury: { accommodation: "$500+/night", food: "$150+/day", activities: "$100+/day" },
    },
  },
  london: {
    name: "London",
    country: "United Kingdom",
    overview:
      "Discover royal palaces, historic landmarks, and vibrant neighborhoods in Britain's capital",
    description: "Ancient history meets modern culture in this world-class metropolis",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    bestTime: "May-September",
    language: "English",
    currency: "GBP",
    timezone: "GMT",
    attractions: [
      {
        name: "Big Ben & Parliament",
        category: "Historical",
        description: "Iconic clock tower and seat of Parliament",
        timeToSpend: "1-2 hours",
        cost: "Free (exterior)",
        openHours: "24/7",
      },
      {
        name: "Tower of London",
        category: "Historical",
        description: "Historic castle and former royal residence",
        timeToSpend: "2-3 hours",
        cost: "$34",
        openHours: "9:00 AM - 5:30 PM",
      },
      {
        name: "Buckingham Palace",
        category: "Royal",
        description: "Official residence of the British monarch",
        timeToSpend: "1-2 hours",
        cost: "$35",
        openHours: "9:30 AM - 3:30 PM",
      },
      {
        name: "Westminster Abbey",
        category: "Religious",
        description: "Stunning Gothic church with royal connections",
        timeToSpend: "1-2 hours",
        cost: "$28",
        openHours: "9:30 AM - 4:30 PM",
      },
      {
        name: "British Museum",
        category: "Museum",
        description: "World-renowned museum of human culture",
        timeToSpend: "3-4 hours",
        cost: "Free",
        openHours: "10:00 AM - 5:30 PM",
      },
    ],
    restaurants: {
      breakfast: [
        {
          name: "Sketch",
          cuisine: "Modern European",
          description: "Artistic venue with Instagram-worthy breakfast",
          priceRange: "$$",
          rating: 4.5,
        },
        {
          name: "The Breakfast Club",
          cuisine: "American",
          description: "Popular brunch spot in Soho",
          priceRange: "$$",
          rating: 4.3,
        },
        {
          name: "Pret A Manger",
          cuisine: "Casual",
          description: "Quick and quality sandwiches",
          priceRange: "$",
          rating: 4.2,
        },
      ],
      lunch: [
        {
          name: "Dishoom",
          cuisine: "Indian",
          description: "Award-winning Indian restaurant",
          priceRange: "$$",
          rating: 4.6,
        },
        {
          name: "Pollen Street Social",
          cuisine: "Modern European",
          description: "Michelin-starred casual dining",
          priceRange: "$$",
          rating: 4.5,
        },
        {
          name: "Momo",
          cuisine: "Moroccan",
          description: "Upscale Moroccan cuisine",
          priceRange: "$$",
          rating: 4.4,
        },
      ],
      dinner: [
        {
          name: "The Ledbury",
          cuisine: "Modern European",
          description: "Two Michelin-star fine dining",
          priceRange: "$$$",
          rating: 4.8,
        },
        {
          name: "The Fat Duck",
          cuisine: "Molecular Gastronomy",
          description: "Three Michelin-star innovative cuisine",
          priceRange: "$$$",
          rating: 4.9,
        },
        {
          name: "Nobu Berkeley Street",
          cuisine: "Japanese Fusion",
          description: "High-end Japanese fusion",
          priceRange: "$$$",
          rating: 4.7,
        },
      ],
    },
    hotels: [
      {
        name: "Claridge's",
        type: "Luxury Hotel",
        location: "Mayfair",
        description: "Legendary art deco hotel",
        pricePerNight: "$450-900",
        rating: 4.7,
        amenities: ["Spa", "Fine Dining", "Bar"],
      },
      {
        name: "Savoy",
        type: "Luxury Hotel",
        location: "Strand",
        description: "Historic riverside luxury hotel",
        pricePerNight: "$500-1000",
        rating: 4.8,
        amenities: ["Spa", "Restaurants", "River Views"],
      },
      {
        name: "The Dorchester",
        type: "Luxury Hotel",
        location: "Mayfair",
        description: "Iconic luxury hotel since 1931",
        pricePerNight: "$400-800",
        rating: 4.7,
        amenities: ["Spa", "Fine Dining", "Bar"],
      },
    ],
    budget: {
      budget: { accommodation: "$60-120/night", food: "$25-40/day", activities: "$20-40/day" },
      medium: { accommodation: "$150-300/night", food: "$60-100/day", activities: "$50-100/day" },
      luxury: { accommodation: "$450+/night", food: "$120+/day", activities: "$80+/day" },
    },
  },
  delhi: {
    name: "Delhi",
    country: "India",
    overview: "Explore India's vibrant capital blending Mughal architecture, bustling markets, and modern culture",
    description: "A city where ancient monuments stand alongside modern developments",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    bestTime: "October-March",
    language: "Hindi, English",
    currency: "INR",
    timezone: "IST",
    attractions: [
      {
        name: "Red Fort",
        category: "Historical",
        description: "Massive Mughal fortress with stunning architecture",
        timeToSpend: "2-3 hours",
        cost: "$5",
        openHours: "9:30 AM - 4:30 PM",
      },
      {
        name: "Taj Mahal (Agra)",
        category: "Monument",
        description: "World's most beautiful building, UNESCO site",
        timeToSpend: "3-4 hours",
        cost: "$20",
        openHours: "6:00 AM - 7:00 PM",
      },
      {
        name: "Jama Masjid",
        category: "Religious",
        description: "One of India's largest mosques",
        timeToSpend: "1-2 hours",
        cost: "$3",
        openHours: "All day",
      },
      {
        name: "India Gate",
        category: "Monument",
        description: "War memorial and popular gathering spot",
        timeToSpend: "1-2 hours",
        cost: "Free",
        openHours: "All day",
      },
      {
        name: "Chandni Chowk",
        category: "Market",
        description: "Historic bazaar with food stalls and shopping",
        timeToSpend: "2-3 hours",
        cost: "Varies",
        openHours: "All day",
      },
    ],
    restaurants: {
      breakfast: [
        {
          name: "Indian Coffee House",
          cuisine: "Indian",
          description: "Traditional Indian breakfast and coffee",
          priceRange: "$",
          rating: 4.2,
        },
        {
          name: "Paranthe Wali Gali",
          cuisine: "Indian",
          description: "Famous street with stuffed bread breakfast",
          priceRange: "$",
          rating: 4.3,
        },
        {
          name: "Café Coffee Day",
          cuisine: "Café",
          description: "Modern café with breakfast options",
          priceRange: "$",
          rating: 4.1,
        },
      ],
      lunch: [
        {
          name: "Karim's",
          cuisine: "Mughlai",
          description: "Famous Mughlai cuisine since 1913",
          priceRange: "$",
          rating: 4.4,
        },
        {
          name: "Haldiram's",
          cuisine: "Indian",
          description: "Popular chain with traditional Indian food",
          priceRange: "$",
          rating: 4.2,
        },
        {
          name: "Nathu's Sweets",
          cuisine: "Indian Sweets",
          description: "Famous for Indian sweets and snacks",
          priceRange: "$",
          rating: 4.3,
        },
      ],
      dinner: [
        {
          name: "Dum Pukht",
          cuisine: "Mughlai",
          description: "Fine dining Mughlai restaurant",
          priceRange: "$$",
          rating: 4.5,
        },
        {
          name: "Bukhara",
          cuisine: "North Indian",
          description: "High-end North Indian cuisine",
          priceRange: "$$",
          rating: 4.4,
        },
        {
          name: "Indian Accent",
          cuisine: "Indian Contemporary",
          description: "Modern Indian fine dining",
          priceRange: "$$",
          rating: 4.6,
        },
      ],
    },
    hotels: [
      {
        name: "The Leela Palace",
        type: "Luxury Hotel",
        location: "New Delhi",
        description: "Ultra-luxury palace hotel",
        pricePerNight: "$250-500",
        rating: 4.8,
        amenities: ["Spa", "Fine Dining", "Pool"],
      },
      {
        name: "Taj Hotel",
        type: "Luxury Hotel",
        location: "Connaught Place",
        description: "Premier luxury hotel in city center",
        pricePerNight: "$200-400",
        rating: 4.7,
        amenities: ["Spa", "Restaurants", "Bar"],
      },
      {
        name: "The Oberoi",
        type: "Luxury Hotel",
        location: "New Delhi",
        description: "Elegant luxury hotel with gardens",
        pricePerNight: "$180-350",
        rating: 4.6,
        amenities: ["Spa", "Fine Dining", "Pool"],
      },
    ],
    budget: {
      budget: { accommodation: "$20-50/night", food: "$8-15/day", activities: "$5-15/day" },
      medium: { accommodation: "$60-150/night", food: "$20-40/day", activities: "$20-40/day" },
      luxury: { accommodation: "$200+/night", food: "$80+/day", activities: "$50+/day" },
    },
  },
}

export type DestinationKey = keyof typeof destinations

export function getDestination(name: string) {
  const key = name.toLowerCase().replace(/\s+/g, "") as DestinationKey
  return destinations[key] || destinations.paris // Default to Paris
}

export function getAllDestinations() {
  return Object.values(destinations).map((d) => ({
    name: d.name,
    country: d.country,
    overview: d.overview,
  }))
}
